### ISSUE TITLE
Fix Koch-Wiki: Links broken

### ISSUE THREAD

**Issue by Overcolor** [openzim/zim-requests#547]
- Website URL: https://library.kiwix.org/viewer#kochwiki_de_all_maxi_2022-12/A/Hauptseite
- ZIM Title: **Koch-Wiki**
- Language (ISO 639-3): **de**

Hi there,
the Links on the "Koch-Wiki" are broken and when you click one you stay on the Main-Page (every link i tried). The search also does not work. You can test it on the official Kiwix-Instance (link above).

**Comment by Popolechien** [comment]
That's odd, I can't find the recipe on the zimfarm. And it's not that the links are broken, but they circle back to the home page.

@RavanJAltaie can you please investigate?
1. Ask for deletion of the existing kochwiki recipes
2. Find the recipe
3. If it does not exist, create it and run a test
4. open a ticket over at /mwoffliner describing the issue if it hasn't been solved with the new run.

**Comment by RavanJAltaie** [comment]
https://library.kiwix.org/viewer#kochwiki_de_all_nopic_2023-01/A/Hauptseite
This link is working, some of links are not active but most of them are working, please check if you can open the links @Popolechien 

This is the recipe for reference 
https://farm.openzim.org/recipes/kochwiki

**Comment by Overcolor** [comment]
@RavanJAltaie The links are still not working for me. For example “Arabischer Bulguersalat”. When I click it, I stay on the Home Page. I didn't find an internal link, which worked. Links to external Websites work.
And some links on the left site are missing, e.g., “Von A bis Z”. It would be useful for coordination on the site.

**Comment by Popolechien** [comment]
Same thing here - recipe links do not work, only external ones.
@RavanJAltaie when restarting faulty recipes on the zim farm do not forget to move them to /.hidden/dev (I just did for kochwiki). 
@rgaudin can you please delete

**Comment by RavanJAltaie** [comment]
@Popolechien noted

**Comment by rgaudin** [comment]
done

**Comment by Popolechien** [comment]
> some links on the left site are missing, e.g., “Von A bis Z”. It would be useful for coordination on the site.

@Overcolor this is a current limitation of mwoffliner, it does not pick up categories.

**Comment by Popolechien** [comment]
@rgaudin 
https://download.kiwix.org/zim/other/kochwiki_de_all_maxi_2023-01.zim and
https://download.kiwix.org/zim/other/kochwiki_de_all_nopic_2023-01.zim

Are still around it seems

**Comment by rgaudin** [comment]
```
[   ] [kochwiki_de_all_maxi_2023-01.zim](https://download.kiwix.org/zim/other/kochwiki_de_all_maxi_2023-01.zim)                              2023-01-18 11:12   56M   
[   ] [kochwiki_de_all_nopic_2023-01.zim](https://download.kiwix.org/zim/other/kochwiki_de_all_nopic_2023-01.zim)                             2023-01-18 10:58   56M
```

created after I deleted them. What should I do? Delete those new ones?

**Comment by Popolechien** [comment]
Yep they're still broken. Was also surprised to see them as recipe points to /dev but whatever.
Thanks

**Comment by rgaudin** [comment]
recipe was changed to dev on thursday during the training

**Comment by rgaudin** [comment]
done
